/// <reference lib="webworker" />
/**
 * Sandbox Worker — executes the JS generated by the souffleurs (pdf / sandbox)
 * in a dedicated Worker. Port of aimi's sandbox.worker, adapted to the v7 contract:
 *  - network and importScripts removed BEFORE any user code;
 *  - `jspdf`: souffleur-pdf's code (jsPDF + autoTable, return doc.output('blob'));
 *  - `compute`: souffleur-sandbox's code — returns a VALUE (number/object/
 *    string/SVG), with the globals announced by the runtime prompt:
 *    math (mathjs), ss (simple-statistics), _ (lodash), dateFns, faker (mini).
 *  - hard timeout on the host side via Worker.terminate().
 */

const networkBlocker = () => {
  throw new Error('Network access is blocked in sandbox');
};
for (const name of [
  'fetch',
  'XMLHttpRequest',
  'WebSocket',
  'EventSource',
  'importScripts',
  'navigator',
]) {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    delete (self as any)[name];
  } catch {
    /* read-only: overwritten below */
  }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const g = self as any;
g.fetch = networkBlocker;
g.XMLHttpRequest = networkBlocker;
g.WebSocket = networkBlocker;
g.EventSource = networkBlocker;
g.importScripts = networkBlocker;

export type SandboxLib = 'jspdf' | 'compute' | 'native';

interface LibBinding {
  globals: Record<string, unknown>;
  mime: string;
}

const cached: Partial<Record<SandboxLib, LibBinding>> = {};

async function loadLib(lib: SandboxLib): Promise<LibBinding> {
  const hit = cached[lib];
  if (hit) return hit;

  let binding: LibBinding;
  switch (lib) {
    case 'jspdf': {
      const { jsPDF } = await import('jspdf');
      // Both forms must work, because the runtime prompt (verbatim from the
      // contract, we don't touch it) announces "Globals: jsPDF, autoTable" while
      // the dataset that trained souffleur-pdf only uses
      // `doc.autoTable({...})` (477/477, lab audit from 26/07 §3). Without
      // `applyPlugin`, the method form crashes; without the global, the function
      // form `autoTable(doc, {...})` that the prompt invites crashes. We expose
      // both: the model can no longer pick the wrong door.
      // `doc.text()` throws "Invalid arguments passed to jsPDF.text" when the
      // text is undefined/null or x/y is NaN — typically a variable the
      // generated code never defined, or a total it never computed. Seen
      // 2026-08-28: one such call failed the whole invoice. A document with one
      // missing line beats no document: coerce numbers to strings, skip the
      // call when it cannot draw anything, and say so in the console.
      // `text` is defined per INSTANCE inside jsPDF's constructor (not on the
      // prototype), hence the construct trap rather than a prototype patch.
      const forgivingText = (doc: { text: (...a: unknown[]) => unknown }) => {
        const original = doc.text.bind(doc);
        doc.text = (...args: unknown[]) => {
          let [text, x, y] = args;
          // Legacy order text(x, y, text): jsPDF swaps it itself, but only when
          // the text is a string — normalise numbers first so it can.
          if (typeof text === 'number' && typeof x === 'number' && typeof y === 'number') {
            [x, y, text] = [text, x, String(y)];
          }
          if (typeof text === 'number') text = String(text);
          if (Array.isArray(text)) text = text.map((t) => (t == null ? '' : String(t)));
          if (text == null || Number.isNaN(Number(x)) || Number.isNaN(Number(y))) {
            console.warn('[sandbox] jsPDF.text skipped: invalid arguments', args);
            return doc;
          }
          return original(text, x, y, ...args.slice(3));
        };
      };
      const ForgivingJsPDF = new Proxy(jsPDF, {
        construct(target, args, newTarget) {
          const doc = Reflect.construct(target, args, newTarget);
          forgivingText(doc);
          return doc;
        },
        apply(target, _thisArg, args) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const doc = new (target as any)(...args);
          forgivingText(doc);
          return doc;
        },
      });
      const globals: Record<string, unknown> = { jsPDF: ForgivingJsPDF };
      try {
        const { applyPlugin, autoTable } = await import('jspdf-autotable');
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        applyPlugin(jsPDF as any);
        globals['autoTable'] = autoTable;
      } catch {
        /* optional plugin — code without a table still works */
      }
      binding = { globals, mime: 'application/pdf' };
      break;
    }
    case 'compute': {
      // Globals from the sandbox_js runtime prompt — lazy (deferred chunks).
      // The REAL @faker-js/faker (fr locale, like the training harness):
      // souffleur-sandbox emits faker.location/commerce/date/etc. that the
      // mini-shim didn't cover.
      const [math, ss, lodash, dateFns, fakerMod] = await Promise.all([
        import('mathjs'),
        import('simple-statistics'),
        import('lodash-es'),
        import('date-fns'),
        import('@faker-js/faker'),
      ]);
      binding = {
        globals: {
          math,
          ss,
          _: lodash,
          dateFns,
          faker: fakerMod.fakerFR ?? fakerMod.faker,
          TextEncoder,
        },
        mime: 'application/json',
      };
      break;
    }
    case 'native':
      binding = { globals: { TextEncoder }, mime: 'application/octet-stream' };
      break;
  }
  cached[lib] = binding;
  return binding;
}

async function toUint8(value: unknown): Promise<Uint8Array> {
  if (value instanceof Uint8Array) return value;
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  if (typeof Blob !== 'undefined' && value instanceof Blob) {
    return new Uint8Array(await value.arrayBuffer());
  }
  const v = value as { buffer?: ArrayBufferLike; byteOffset?: number; byteLength?: number };
  if (v && v.buffer instanceof ArrayBuffer && typeof v.byteLength === 'number') {
    return new Uint8Array(v.buffer, v.byteOffset ?? 0, v.byteLength);
  }
  throw new Error(`Generated value is not a binary type (got ${typeof value})`);
}

self.addEventListener('message', async (event: MessageEvent) => {
  const { type, id, lib, code } = event.data ?? {};
  if (type !== 'exec') return;

  let binding: LibBinding;
  try {
    binding = await loadLib(lib as SandboxLib);
  } catch (err) {
    self.postMessage({ type: 'exec-error', id, message: String(err), phase: 'load' });
    return;
  }

  const paramNames = Object.keys(binding.globals);
  const paramValues = paramNames.map((n) => binding.globals[n]);

  let userFn: (...args: unknown[]) => Promise<unknown>;
  try {
    const AsyncFunction = async function () {}.constructor as new (
      ...args: string[]
    ) => (...a: unknown[]) => Promise<unknown>;
    userFn = new AsyncFunction(...paramNames, code);
  } catch (err) {
    self.postMessage({
      type: 'exec-error',
      id,
      message: `Compile error: ${String(err)}`,
      phase: 'exec',
    });
    return;
  }

  try {
    const result = await userFn(...paramValues);
    if (lib === 'compute') {
      let value: string;
      try {
        value = typeof result === 'string' ? result : JSON.stringify(result);
      } catch {
        value = String(result);
      }
      self.postMessage({ type: 'exec-ok', id, value, mime: binding.mime });
      return;
    }
    const data = await toUint8(result);
    self.postMessage({ type: 'exec-ok', id, data, mime: binding.mime }, [data.buffer]);
  } catch (err) {
    self.postMessage({ type: 'exec-error', id, message: String(err), phase: 'exec' });
  }
});
