/**
 * Correlation tool_call → produced artifact (for the renderers) + persistence
 * sink wired in by the app (the souffleurs module doesn't know about Dexie).
 */

export interface ProducedArtifact {
  kind: string;
  filename: string;
  mime: string;
  blob: Blob;
  /** Preview HTML generated by OUR runtimes (escaped content). */
  preview: string;
  opsCount?: number;
}

export interface ProducedWidget {
  kind: 'html' | 'svg' | 'chart' | 'code';
  content: string;
}

export const artifactsByCall = new Map<string, ProducedArtifact>();
export const widgetsByCall = new Map<string, ProducedWidget>();

type ArtifactSink = (toolCallId: string, artifact: ProducedArtifact, fileId: string) => void;
type ArtifactLoader = (toolCallId: string) => Promise<ProducedArtifact | null>;
let sink: ArtifactSink | null = null;
let loader: ArtifactLoader | null = null;

/** The app wires persistence in here (Dexie artifacts table, future gallery). */
export function setArtifactSink(fn: ArtifactSink): void {
  sink = fn;
}

/** The app wires RE-hydration in here (after a reload, the in-memory Map is empty). */
export function setArtifactLoader(fn: ArtifactLoader): void {
  loader = fn;
}

/** A tool_call's artifact: in-memory Map first, otherwise persistence (reload). */
export async function loadArtifact(toolCallId: string): Promise<ProducedArtifact | null> {
  const hit = artifactsByCall.get(toolCallId);
  if (hit) return hit;
  try {
    const fromStore = await loader?.(toolCallId);
    if (fromStore) artifactsByCall.set(toolCallId, fromStore);
    return fromStore ?? null;
  } catch {
    return null;
  }
}

export function notifyArtifact(
  toolCallId: string,
  artifact: ProducedArtifact,
  fileId: string,
): void {
  artifactsByCall.set(toolCallId, artifact);
  try {
    sink?.(toolCallId, artifact, fileId);
  } catch (err) {
    console.warn('[souffleurs] artifact sink error', err);
  }
}

/* ── LIVE preview during generation (iso aimi: the document builds up in
 *    front of the user's eyes while the executor streams) ── */

export interface LiveArtifactState {
  /** Preview HTML (escaped by our runtimes) — xlsx/docx. */
  html?: string;
  /** Code being generated (shown as plain text) — pdf. */
  code?: string;
}

const liveByCall = new Map<string, LiveArtifactState>();
const liveListeners = new Map<string, (state: LiveArtifactState) => void>();

export function pushLiveArtifact(toolCallId: string, patch: LiveArtifactState): void {
  const state = { ...liveByCall.get(toolCallId), ...patch };
  liveByCall.set(toolCallId, state);
  liveListeners.get(toolCallId)?.(state);
}

export function subscribeLiveArtifact(
  toolCallId: string,
  listener: (state: LiveArtifactState) => void,
): void {
  liveListeners.set(toolCallId, listener);
  const current = liveByCall.get(toolCallId);
  if (current) listener(current);
}

export function clearLiveArtifact(toolCallId: string): void {
  liveByCall.delete(toolCallId);
  liveListeners.delete(toolCallId);
}

export function triggerDownload(blob: Blob, filename: string): void {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 10_000);
}
